<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.7 ./models/environment/nature/tree_single_A.gltf --types --shadows --transform
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, InstancedMesh, Instance, useTexture, useDraco } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		transformData,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		transformData: [number, number, number, number][];
	} = $props();

	type GLTFResult = {
		nodes: {
			tree_single_A: THREE.Mesh;
		};
		materials: {
			hexagons_medieval: THREE.MeshStandardMaterial;
		};
	};

	import Model from './tree_single_A-transformed.glb?url';
	import Texture from '$lib/assets/textures/nature.png?url';
	const draco = useDraco();
	const gltf = useGltf<GLTFResult>(Model, { dracoLoader: draco });
	//export let transformData: [number, number, number, number][] = [];

	const texture = useTexture(Texture);
	const assets = Promise.all([gltf, texture]);
</script>

<!-- 
<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.tree_single_A.geometry}
			material={gltf.materials.hexagons_medieval}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
 -->

{#await assets}
	{@render fallback?.()}
{:then [agltf, atexture]}
	<InstancedMesh>
		<T is={agltf.nodes.tree_single_A.geometry} />
		<T.MeshStandardMaterial map={atexture} />
		{#each transformData as randomValues}
			{@const x = randomValues[0] - 10}
			{@const z = randomValues[1] - 10}
			{@const scale = randomValues[3] * 2 + 5}
			<T.Group position.x={x} position.y={1} position.z={z} rotation.y={90} {scale}>
				<Instance rotation={[0, 0, 0]} />
			</T.Group>
		{/each}
	</InstancedMesh>
{/await}
