<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.7 ./models/buildings/blue/building_blacksmith_blue.gltf --types --shadows --transform
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useDraco } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			building_blacksmith_blue: THREE.Mesh;
		};
		materials: {
			hexagons_medieval: THREE.MeshStandardMaterial;
		};
	};
	const draco = useDraco();

	import Model from './building_blacksmith_blue-transformed.glb?url';
	const gltf = useGltf<GLTFResult>(Model, { dracoLoader: draco });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.building_blacksmith_blue.geometry}
			material={gltf.materials.hexagons_medieval}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
