<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.7 ./models/npc/tavern/Barbarian.glb --types --shadows --transform
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { onMount, type Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useDraco, useGltf, useGltfAnimations } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	ref = new Group();

	type ActionName =
		| '1H_Melee_Attack_Chop'
		| '1H_Melee_Attack_Slice_Diagonal'
		| '1H_Melee_Attack_Slice_Horizontal'
		| '1H_Melee_Attack_Stab'
		| '1H_Ranged_Aiming'
		| '1H_Ranged_Reload'
		| '1H_Ranged_Shoot'
		| '1H_Ranged_Shooting'
		| '2H_Melee_Attack_Chop'
		| '2H_Melee_Attack_Slice'
		| '2H_Melee_Attack_Spin'
		| '2H_Melee_Attack_Spinning'
		| '2H_Melee_Attack_Stab'
		| '2H_Melee_Idle'
		| '2H_Ranged_Aiming'
		| '2H_Ranged_Reload'
		| '2H_Ranged_Shoot'
		| '2H_Ranged_Shooting'
		| 'Block'
		| 'Block_Attack'
		| 'Block_Hit'
		| 'Blocking'
		| 'Cheer'
		| 'Death_A'
		| 'Death_A_Pose'
		| 'Death_B'
		| 'Death_B_Pose'
		| 'Dodge_Backward'
		| 'Dodge_Forward'
		| 'Dodge_Left'
		| 'Dodge_Right'
		| 'Dualwield_Melee_Attack_Chop'
		| 'Dualwield_Melee_Attack_Slice'
		| 'Dualwield_Melee_Attack_Stab'
		| 'Hit_A'
		| 'Hit_B'
		| 'Idle'
		| 'Interact'
		| 'Jump_Full_Long'
		| 'Jump_Full_Short'
		| 'Jump_Idle'
		| 'Jump_Land'
		| 'Jump_Start'
		| 'Lie_Down'
		| 'Lie_Idle'
		| 'Lie_Pose'
		| 'Lie_StandUp'
		| 'PickUp'
		| 'Running_A'
		| 'Running_B'
		| 'Running_Strafe_Left'
		| 'Running_Strafe_Right'
		| 'Sit_Chair_Down'
		| 'Sit_Chair_Idle'
		| 'Sit_Chair_Pose'
		| 'Sit_Chair_StandUp'
		| 'Sit_Floor_Down'
		| 'Sit_Floor_Idle'
		| 'Sit_Floor_Pose'
		| 'Sit_Floor_StandUp'
		| 'Spellcast_Long'
		| 'Spellcast_Raise'
		| 'Spellcast_Shoot'
		| 'Spellcasting'
		| 'T-Pose'
		| 'Throw'
		| 'Unarmed_Idle'
		| 'Unarmed_Melee_Attack_Kick'
		| 'Unarmed_Melee_Attack_Punch_A'
		| 'Unarmed_Melee_Attack_Punch_B'
		| 'Unarmed_Pose'
		| 'Use_Item'
		| 'Walking_A'
		| 'Walking_B'
		| 'Walking_Backwards'
		| 'Walking_C';
	type GLTFResult = {
		nodes: {
			['1H_Axe_Offhand']: THREE.Mesh;
			Barbarian_Round_Shield: THREE.Mesh;
			['1H_Axe']: THREE.Mesh;
			['2H_Axe']: THREE.Mesh;
			Mug: THREE.Mesh;
			Barbarian_Hat: THREE.Mesh;
			Barbarian_Cape: THREE.Mesh;
			Barbarian_ArmLeft: THREE.SkinnedMesh;
			Barbarian_ArmRight: THREE.SkinnedMesh;
			Barbarian_Body: THREE.SkinnedMesh;
			Barbarian_Head: THREE.SkinnedMesh;
			Barbarian_LegLeft: THREE.SkinnedMesh;
			Barbarian_LegRight: THREE.SkinnedMesh;
			root: THREE.Bone;
		};
		materials: {
			barbarian_texture: THREE.MeshStandardMaterial;
			barbarian_texture: THREE.MeshStandardMaterial;
		};
	};

	import Model from './Tavern-transformed.glb?url';

	const draco = useDraco();
	const gltf = useGltf<GLTFResult>(Model, { dracoLoader: draco });

	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	onMount(() => {
		actions.subscribe((v) => {
			if (v) {
				$actions['Idle']?.play();
			}
		});
	});
</script>

<T is={ref} dispose={false} {...props} scale={0.5} rotation.y={0.75*Math.PI} position.y={-0.75}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Rig">
				<T is={gltf.nodes.root} />
				<T.SkinnedMesh
					name="Barbarian_ArmLeft"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Barbarian_ArmLeft.geometry}
					material={gltf.materials.barbarian_texture}
					skeleton={gltf.nodes.Barbarian_ArmLeft.skeleton}
				/>
				<T.SkinnedMesh
					name="Barbarian_ArmRight"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Barbarian_ArmRight.geometry}
					material={gltf.materials.barbarian_texture}
					skeleton={gltf.nodes.Barbarian_ArmRight.skeleton}
				/>
				<T.SkinnedMesh
					name="Barbarian_Body"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Barbarian_Body.geometry}
					material={gltf.materials.barbarian_texture}
					skeleton={gltf.nodes.Barbarian_Body.skeleton}
				/>
				<T.SkinnedMesh
					name="Barbarian_Head"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Barbarian_Head.geometry}
					material={gltf.materials.barbarian_texture}
					skeleton={gltf.nodes.Barbarian_Head.skeleton}
				/>
				<T.SkinnedMesh
					name="Barbarian_LegLeft"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Barbarian_LegLeft.geometry}
					material={gltf.materials.barbarian_texture}
					skeleton={gltf.nodes.Barbarian_LegLeft.skeleton}
				/>
				<T.SkinnedMesh
					name="Barbarian_LegRight"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Barbarian_LegRight.geometry}
					material={gltf.materials.barbarian_texture}
					skeleton={gltf.nodes.Barbarian_LegRight.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
